site_name: 茗苕芝士铺
site_description: ZJUer的个人知识网站
site_author: wlm
site_url: https://mingshaoai.xyz
repo_url: https://github.com/wwoozyq/mingshao-notes
repo_name: wwoozyq/mingshao-notes

theme:
  name: material
  language: zh
  font: false
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换暗色模式
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换亮色模式
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips
    - toc.follow

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 首页: index.md
  - AI:
      - AI 总览: ai/index.md
      - 模式识别与机器学习: ai/pattern-recognition-and-ml.md
      - 自然语言处理: ai/nlp.md
  - 生物医学:
      - 生物医学总览: biomedical/index.md
      - 生物医学图像处理: biomedical/biomedical-image-processing.md
  - 数学基础:
      - 数学总览: math/index.md
      - 离散数学:
          - 总览: math/discrete-mathematics/index.md
          - 1.集合论: math/discrete-mathematics/01-集合论.md
          - 2.二元关系: math/discrete-mathematics/02-二元关系.md
          - 函数: math/discrete-mathematics/03-函数.md
          - 初等数论: math/discrete-mathematics/04-初等数论.md
          - 图的基本概念: math/discrete-mathematics/05-图的基本概念.md
          - 欧拉图与哈密顿图: math/discrete-mathematics/06-欧拉图与哈密顿图.md
          - 树: math/discrete-mathematics/07-树.md
          - 平面图: math/discrete-mathematics/08-平面图.md
          - 支配集独立集匹配与着色: math/discrete-mathematics/09-支配集独立集匹配与着色.md
          - 命题逻辑: math/discrete-mathematics/10-命题逻辑.md
          - 一阶逻辑: math/discrete-mathematics/11-一阶逻辑.md
  
  - 计算机:
    - 计算机总览: computer/index.md
    - 数据结构基础:
      - 总览: computer/fds/cs-fundamentals.md
      - 一、算法分析: computer/fds/algorithm-analysis.md
      - 并查集: computer/fds/union-find.md
      - 线段树: computer/fds/segment-tree.md
      - 图的定义与拓扑排序: computer/fds/graph-topological-sort.md
      - 最短路径算法: computer/fds/shortest-path.md
      - 编程错题本: computer/fds/error-notebook.md
    - Hot100 刷题: computer/hot100.md
  - 工具:
      - 在线视频播放: tools/video-player.md
  - 留学:
      - 留学总览: study-abroad/index.md
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
