site_name: 茗苕芝士铺
site_description: 聚合 AI、数学基础、留学与计算机笔记的个人知识网站
site_author: wlm
# 部署后建议改成你自己的正式域名
site_url: https://mingshaoai.xyz
repo_url: https://github.com/wwoozyq/mingshao-notes
repo_name: wwoozyq/mingshao-notes

theme:
  name: material
  language: zh
  font: false
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 首页: index.md
  - AI:
      - AI 总览: ai/index.md
      - 学习路线: ai/learning-roadmap.md
      - 模式识别与机器学习: ai/pattern-recognition-and-ml.md
      - 自然语言处理: ai/nlp.md
  - 数学基础:
      - 数学总览: math/index.md
  - 留学:
      - 留学总览: study-abroad/index.md
      - 港新申请规划: study-abroad/application-plan.md
  - 计算机:
      - 计算机总览: computer/index.md
      - 数据结构基础:computer/cs-fundamentals.md
          - 并查集: computer/fds/union-find.md
      - Hot100 刷题: computer/hot100.md
  - 日志:
      - 更新记录: journal/index.md
  - 关于: about.md

extra_css:
  - stylesheets/extra.css
